#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 [domain-name]" 1>&2
    exit
fi

nocache=0

domains=()
for d in $@; do
    case $d in
    "--no-cache")
        nocache=1
        ;;
    *)
        domains+=($d)
        ;;
    esac
done

dir=$(dirname $0)
cache_dir="$dir/whois-cache"

if [[ ! -d $cache_dir ]]; then
    mkdir -p "$cache_dir"
fi

for domain in ${domains[@]}; do

    # [1] is the domain name is valid?
    if [[ "$(echo "$domain" | grep -e '^[a-z0-9]\([a-z0-9\-]*[a-z0-9]\)\?\.\(com\|net\|org\|info\|biz\|us\|co.uk\|co\.kr\|ne\.kr\|or\.kr\|kr\)$')" != "$domain" ]]; then
        echo "ERROR: domain \"$domain\" not supported" 1>&2
        exit
    fi

    # [2] whois lookup
    if [[ "$nocache" -ne 0 ]] || [[ ! -f "$cache_dir/$domain" ]]; then
        # rate limit
        case $domain in
        *.kr)
            if [[ "$(find "$cache_dir/" -name *.kr -ctime -1 | wc -l)" -gt 100 ]]; then
                echo "$domain too many .KR lookup!" 1>&2
                exit
            fi
            ;;
        *.org)
            if [[ "$(find "$cache_dir/" -name *.org -ctime -1 | wc -l)" -gt 100 ]]; then
                echo "$domain too many .ORG lookup!" 1>&2
                exit
            fi
            ;;
        *.info)
            if [[ "$(find "$cache_dir/" -name *.org -ctime -1 | wc -l)" -gt 100 ]]; then
                echo "$domain too many .INFO lookup!" 1>&2
                exit
            fi
            ;;
        esac

        # lookup
        case $domain in
        *.com|*.net)
            whois --no-recursion $domain > "$cache_dir/$domain"
            ;;
        *)
            whois $domain > "$cache_dir/$domain"
            ;;
        esac
    fi

    # [3] show the creation date from cache
    reg=""
    case $domain in
    *.com|*.net)
        reg="$(cat "$cache_dir/$domain" | grep 'Creation Date:' | sed 's/^Creation\ Date:\ //' | grep -o "[0-9]\+-[0-9]\+-[0-9]\+")"
        ;;
    *.org|*.info|*.biz|*.us)
        reg="$(cat "$cache_dir/$domain" | grep 'Creation Date:' | sed 's/^Creation\ Date:\ //' | grep -o "[0-9]\+-[0-9]\+-[0-9]\+" | head -1)"
        ;;
    *.uk)
        reg="$(cat "$cache_dir/$domain" | grep 'Registered on:' | sed -e "s/^.\+\ before Aug-1996$/before 08-1996/" \
            -e "s/^.\+\([0-9]\{2\}\)-\([A-Z][a-z]\{2\}\)-\([0-9]\{4\}\)/\3-\2-\1/" \
            -e "s/\-Jan\-/\-01\-/" -e "s/\-Feb\-/\-02\-/" -e "s/\-Mar\-/\-03\-/" -e "s/\-Apr\-/\-04\-/" -e "s/\-May\-/\-05\-/" -e "s/\-Jun\-/\-06\-/" \
            -e "s/\-Jul\-/\-07\-/" -e "s/\-Aug\-/\-08\-/" -e "s/\-Sep\-/\-09\-/" -e "s/\-Oct\-/\-10\-/" -e "s/\-Nov\-/\-11\-/" -e "s/\-Dec\-/\-12\-/")"
        ;;
    *.kr)
        reg="$(cat "$cache_dir/$domain" | grep 'Registered Date' | sed "s/^.\+\([0-9]\{4\}\)\.\ \([0-9]\{2\}\)\.\ \([0-9]\{2\}\)\./\1-\2-\3/")"
        ;;
    *)
        reg="$(cat "$cache_dir/$domain")"
        ;;
    esac

    extlen=$(echo "$domain" | grep -o '\..\+$' | wc -c)
    spaces=""
    case $extlen in
    3)
        spaces="     "
        ;;
    4)
        spaces="    "
        ;;
    5)
        spaces="   "
        ;;
    6)
        spaces="  "
        ;;
    7)
        spaces=" "
        ;;
    *)
        spaces=""
        ;;
    esac

    if [[ -n "$reg" ]]; then
        echo "$domain$spaces $reg"
    else
        echo "$domain$spaces *** available ***"
    fi

done
